### ISSUE TITLE
Querio v1.0

### ISSUE THREAD

**Issue by enkot** [enkot/querio#18]
# Road to Querio v1.0 😎 
Reimplement almost from scratch:

- [x] Fresh look 🎨 
- [x] Simplified and improved requests parsing
- [x] [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/)
- [x] Typescript
- [x] Vue 3 + Vite
- [x] UnoCSS
- [x] [RadixVue](https://www.radix-vue.com/) primitives

New features:
- [x] Last request mode - https://github.com/enkot/querio/issues/10
- [x] GraphQL HTTP batching - https://github.com/enkot/querio/issues/17
- [x] Preflight headers for request/response - https://github.com/enkot/querio/issues/19
- [x] Reimplement search - https://github.com/enkot/querio/issues/20
